# Generated automatically from Makefile.in by configure.
# Makefile template for libsidplay.

version 		= 1.36.28
majorversion 	= 1.36

SHELL			= /bin/sh

BASEDIR			= .
SRCDIR			= $(BASEDIR)
prefix			= /usr
exec_prefix		= ${prefix}
bindir			= ${exec_prefix}/bin
libdir          = ${exec_prefix}/lib
includedir      = ${prefix}/include
includedest     = $(includedir)/sidplay
DOCDIR			= $prefix/doc

CXX				= c++
CXXFLAGS		= -g -O2
LN			    = ln -s
RM              = /bin/rm
AR              = /usr/bin/ar
RANLIB			= ranlib
INSTALL			= /usr/bin/install -c
INSTALL_DATA	= ${INSTALL} -m 644

LDFLAGS			= 
DEFS			= -DHAVE_CONFIG_H
INCLUDES		= -I$(SRCDIR) -I$(SRCDIR)/emu -I$(SRCDIR)/include

LIBM			= -lm
LIBIOS			= 
LIBS			=  $(LIBM) $(LIBIOS)

#--------------------------------------------------------------

srcdirs = . emu fformat include

sources = emu/6510_.cpp emu/6581_.cpp emu/envelope.cpp emu/mixing.cpp emu/samples.cpp \
		fformat/fformat_.cpp fformat/info_.cpp fformat/mus_.cpp fformat/pp_.cpp \
		fformat/psid_.cpp fformat/sid_.cpp \
		eeconfig.cpp player.cpp sidtune.cpp

srcobjs = emu/6510_.o emu/6581_.o emu/envelope.o emu/mixing.o emu/samples.o  \
		fformat/fformat_.o fformat/info_.o fformat/mus_.o fformat/pp_.o  \
		fformat/psid_.o fformat/sid_.o \
		eeconfig.o player.o sidtune.o

install_headers = include/compconf.h include/config.h include/emucfg.h \
		include/fformat.h include/myendian.h include/mytypes.h \
		include/player.h include/sidtune.h include/version.h \
		include/fixpoint.h

.EXPORT_ALL_VARIABLES:

.SUFFIXES:
.SUFFIXES: .cpp .h .o

%.o:	%.cpp
		$(CXX) $(CXXFLAGS) $(INCLUDES) $(DEFS) -c $< -o $@

.PHONY: all
all:	engine libsidplay.a

engine: $(srcobjs)

libsidplay.a: $(srcobjs)
		$(RM) -f libsidplay.a
		$(AR) crv libsidplay.a $(srcobjs)
		$(RANLIB) libsidplay.a

libsidplay.so: $(srcobjs)
		$(CXX) -shared -Wl,-soname,libsidplay.so.$(majorversion) \
		-o libsidplay.so $(srcobjs)

.PHONY: clean
clean:
		@for subdir in $(srcdirs); do \
			(cd $$subdir && $(RM) -f *.d *.o *~ *.a *.so) || exit 1; \
		done

.PHONY: depend
depend:
		makedepend $(INCLUDES) $(sources) 2> /dev/null

.PHONY: install
install:	install-headers install-static

install-static:
		$(INSTALL) -d -m 755 $(libdir)
		$(INSTALL_DATA) libsidplay.a $(libdir)/libsidplay.a

install-headers:
		$(RM) -f $(includedest)/*
		$(INSTALL) -d -m 755 $(includedest)
		for file in $(install_headers); do \
			($(INSTALL_DATA) $$file $(includedest) ) || exit 1; \
		done

install-shared:
		$(INSTALL) -d -m 755 $(libdir)
		$(INSTALL_DATA) libsidplay.so $(libdir)/libsidplay.so.$(version)
		$(RM) -f $(libdir)/libsidplay.so.$(majorversion)
		$(RM) -f $(libdir)/libsidplay.so
		$(LN) -sfv libsidplay.so.$(version) $(libdir)/libsidplay.so.$(majorversion)
		$(LN) -sfv libsidplay.so.$(version) $(libdir)/libsidplay.so

#--------------------------------------------------------------
# DO NOT DELETE THIS LINE -- make depend depends on it.

