# Generated automatically from Makefile.in by configure.

SHELL			= /bin/sh

TOPDIR			= ..
BASEDIR			= .
SRCDIR			= $(BASEDIR)
prefix			= /usr
exec_prefix		= ${prefix}
bindir			= ${exec_prefix}/bin
libdir			= ${exec_prefix}/lib
includedir		= ${prefix}/include
DOCDIR			= $prefix/doc

CXX				= c++
CXXFLAGS		= -g -O2
LN				= ln -s
RM				= /bin/rm
AR				= /usr/bin/ar
RANLIB			= ranlib
INSTALL			= /usr/bin/install -c
INSTALL_DATA	= ${INSTALL} -m 644

LDFLAGS			= 
DEFS			= -DHAVE_CONFIG_H
INCLUDES		= -I$(SRCDIR) -I$(TOPDIR)/libsidplay/include

LIBM			= -lm
LIBIOS			= 
SIDLIB          = -L$(TOPDIR)/libsidplay -lsidplay
LIBS			=  $(LIBM) $(LIBIOS) $(SIDLIB)

#--------------------------------------------------------------

sources =  sidplay.cpp audiodrv.cpp sid2wav.cpp sidcon.cpp

.PHONY: all
all:	sidplay sid2wav sidcon

sidplay:	sidplay.o audiodrv.o
		$(CXX) -o $@ $(LDFLAGS) sidplay.o audiodrv.o $(LIBS)

sid2wav:	sid2wav.o
		$(CXX) -o $@ $(LDFLAGS) sid2wav.o $(LIBS)

sidcon:	sidcon.o
		$(CXX) -o $@ $(LDFLAGS) sidcon.o $(LIBS)

.PHONY: clean
clean:
		rm -f *.d *.o *~ sidplay sid2wav sidcon

.PHONY: depend
depend:
		makedepend $(INCLUDES) $(sources) 2> /dev/null

install:
		$(INSTALL) sidplay $(bindir)
		$(INSTALL) sid2wav $(bindir)
		$(INSTALL) sidcon $(bindir)

.EXPORT_ALL_VARIABLES:

.SUFFIXES:
.SUFFIXES: .cpp .d .h .o

%.o:	%.cpp
		$(CXX) $(CXXFLAGS) $(INCLUDES) $(DEFS) -c $< -o $@

# ---------------------------------------------------------------------------
# DO NOT DELETE THIS LINE -- make depend depends on it.

